### ISSUE TITLE
HTTP Method Pickiness

### ISSUE THREAD

**Issue by derekdowling** [abramhindle/CMPUT404-assignment-webserver#3]
Does our little web server need to be stingy about HTTP version and only serving files if a GET request is issued? Or should we be agnostic to the specified method(DELETE/POST/etc)? This isn't covered in requirements.org so I just thought I'd clarify.

**Comment by abramhindle** [comment]
Well it should support HTTP/1.1 and HTTP/1.0. DELETE/POST should not be allowed. It's an inappropriate method.
